version: '1.0'
services:
  notion2hexo:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: notion2hexo
    ports:
      - 5000:5000
    environment:
      - HEXO_BLOG=/usr/src/app/blog
      - SECRET_KEY=deploynotion
    volumes:
      - /root/grainmad_blog:/usr/src/app/blog
